### ISSUE TITLE
Missing Personnel Data Week 4 NFL 

### ISSUE THREAD

**Issue by jwald3** [cooperdff/nfl_data_py#37] opened 2022-10-04 01:04 UTC
It appears that the values for formation data (offense/defense), players on the play (offense/defense), men in the box, # of pass rushers, etc. are unavailable for 2022 Week 4 data (which is otherwise available). Is this a known issue, an intentional omission, or something else? Where is this data sourced from?

Wondering if it will be available in the near future or if that is a result of an availability issue

**Comment by jwald3** [comment] 2022-10-04 01:56
Scratch that, the data appears to be available in the "load_participation" dataset in nflverse.

**Comment by alecglen** [comment] 2023-07-14 21:29
Hey @jwald3, catching up on this finally! If you recall, could you please elaborate on what you meant? Which module function were you calling that was missing this data?

**Comment by alecglen** [comment] 2023-07-30 20:19
Closing as unable to reproduce / possibly resolved upstream.
<img width="807" alt="image" src="https://github.com/cooperdff/nfl_data_py/assets/28493454/bd8393a3-6c4c-4253-937c-9452e59da005">

**Closed by alecglen** 2023-07-30 20:19 UTC
Labels: bug, question
