### ISSUE TITLE
Unable to import data

### ISSUE THREAD

**Issue by samob917** [cooperdff/nfl_data_py#23] opened 2022-04-06 20:18 UTC
I am trying to run 
`
import nfl_data_py as nfl

nfl.import_seasonal_data([2010])
`

but I get the following error: 
OverflowError: value too large
Exception ignored in: 'fastparquet.cencoding.read_bitpacked'

I have tried uninstalling and reinstalling fastparquet, which did not work, and the same issue has arisen in my other function calls.

More specifically: 
 `line 530, in read_col
    part[defi == max_defi] = dic[val]`

IndexError: index 8389024 is out of bounds for axis 0 with size 94518

**Comment by cooperdff** [comment] 2022-05-01 00:22
Could one or both of you provide me with the details of the environment you're running? I am unable to reproduce this issue on my system so may just need to change some package versions around.

**Comment by samob917** [comment] 2022-05-01 15:44
I was using spyder environment on windows!

-Sam Oberly

________________________________

**Comment by samob917** [comment] 2022-05-04 23:12
~\AppData\Roaming\Python\Python310\site-packages\nfl_data_py\__init__.py in import_weekly_data(years, columns, downcast)
    217 
    218     # read weekly data
--> 219     data = pandas.read_parquet(r'https://github.com/nflverse/nflfastR-data/raw/master/data/player_stats.parquet', engine='auto')
    220     data = data[data['season'].isin(years)]
    221 

~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parquet.py in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)
    491     impl = get_engine(engine)
    492 
--> 493     return impl.read(
    494         path,
    495         columns=columns,
More specifically, this is the error:
`
~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parquet.py in read(self, path, columns, storage_options, **kwargs)
    345         parquet_file = self.api.ParquetFile(path, **parquet_kwargs)
    346 
--> 347         result = parquet_file.to_pandas(columns=columns, **kwargs)
    348 
    349         if handles is not None:

~\AppData\Local\Programs\Python\Python310\lib\site-packages\fastparquet\api.py in to_pandas(self, columns, categories, filters, index, row_filter)
    749                             else v[start:start + thislen])
    750                      for (name, v) in views.items()}
--> 751             self.read_row_group_file(rg, columns, categories, index,
    752                                      assign=parts, partition_meta=self.partition_meta,
    753                                      row_filter=sel, infile=infile)

~\AppData\Local\Programs\Python\Python310\lib\site-packages\fastparquet\api.py in read_row_group_file(self, rg, columns, categories, index, assign, partition_meta, row_filter, infile)
    359         f = infile or self.open(fn, mode='rb')
    360 
--> 361         core.read_row_group(
    362             f, rg, columns, categories, self.schema, self.cats,
    363             selfmade=self.selfmade, index=index,

~\AppData\Local\Programs\Python\Python310\lib\site-packages\fastparquet\core.py in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, scheme, partition_meta, row_filter)
    606     if assign is None:
    607         raise RuntimeError('Going with pre-allocation!')
--> 608     read_row_group_arrays(file, rg, columns, categories, schema_helper,
    609                           cats, selfmade, assign=assign, row_filter=row_filter)
    610 

~\AppData\Local\Programs\Python\Python310\lib\site-packages\fastparquet\core.py in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign, row_filter)
    578             continue
    579 
--> 580         read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
    581                  selfmade=selfmade, assign=out[name],
    582                  catdef=out.get(name+'-catdef', None),

~\AppData\Local\Programs\Python\Python310\lib\site-packages\fastparquet\core.py in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef, row_filter)
    528                 part[defi != max_defi] = my_nan
    529             if d and not use_cat:
--> 530                 part[defi == max_defi] = dic[val]
    531             elif not use_cat:
    532                 part[defi == max_defi] = convert(val, se)

IndexError: index 8389024 is out of bounds for axis 0 with size 94518
`

**Comment by cooperdff** [comment] 2022-06-04 20:08
Finally had some time to dig into this. Looks like it was an issue with the size of data being pulled. I've updated the process in the latest release - please try uninstalling your current version and upgrading to 0.2.7 and let me know if it fixes things.

**Comment by cooperdff** [comment] 2022-07-30 00:56
Closing pending further issues.

**Closed** 2022-07-30 00:56 UTC
